name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Build binaries
        run: |
          mkdir dist
          GOOS=linux GOARCH=amd64 go build -o dist/filecompressor-linux-amd64 ./cmd/filecompressor
          GOOS=linux GOARCH=arm64 go build -o dist/filecompressor-linux-arm64 ./cmd/filecompressor
          GOOS=darwin GOARCH=amd64 go build -o dist/filecompressor-darwin-amd64 ./cmd/filecompressor
          GOOS=darwin GOARCH=arm64 go build -o dist/filecompressor-darwin-arm64 ./cmd/filecompressor
          GOOS=windows GOARCH=amd64 go build -o dist/filecompressor-windows-amd64.exe ./cmd/filecompressor
          GOOS=windows GOARCH=arm64 go build -o dist/filecompressor-windows-arm64.exe ./cmd/filecompressor

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
